/* Generated By:JavaCC: Do not edit this line. SiteswapParserConstants.java */
package jugglinglab.notation;

public interface SiteswapParserConstants {

  int EOF = 0;
  int NUM = 4;
  int LET = 5;
  int MOD = 6;
  int SPC = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUM>",
    "<LET>",
    "<MOD>",
    "<SPC>",
    "\"*\"",
    "\"(\"",
    "\"^\"",
    "\")\"",
    "\"!\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"p\"",
    "\"x\"",
    "\"/\"",
    "\"R\"",
    "\"L\"",
    "\"<\"",
    "\"|\"",
    "\">\"",
    "\"?\"",
  };

}
